<a href="https://colab.research.google.com/github/dmaresza/tensorflow_course/blob/main/00_TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises

In [ ]:
import tensorflow as tf
import numpy as np

## 1. Create a scalar, vector, matrix, and tensor with values of your choosing using `tf.constant()`.

In [ ]:
scalar = tf.constant(np.random.randint(0, 100, size=1))
vector = tf.constant(np.random.randint(0, 100, size=3))
matrix = tf.constant(np.random.randint(0, 100, size=12), shape=(4, 3))
tensor = tf.constant(np.random.randint(0, 100, size=120), shape=(2, 3, 4, 5))

scalar, vector, matrix, tensor

(<tf.Tensor: shape=(1,), dtype=int64, numpy=array([96])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([75,  5, 78])>,
 <tf.Tensor: shape=(4, 3), dtype=int64, numpy=
 array([[96, 51, 38],
        [15,  2, 15],
        [49, 59, 19],
        [37, 22, 93]])>,
 <tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
 array([[[[45, 20, 52, 24, 67],
          [ 9,  6, 96, 92, 27],
          [52, 17, 64, 96, 55],
          [62, 12, 29, 93, 47]],
 
         [[49, 42, 33, 26, 48],
          [39, 62, 36,  2, 85],
          [29, 67,  9, 30,  2],
          [37, 16, 27, 46, 87]],
 
         [[99, 21, 78,  7, 26],
          [23,  5, 43, 54,  5],
          [31,  6, 35, 10, 60],
          [61, 61, 20, 95, 56]]],
 
 
        [[[41, 75, 61, 12, 15],
          [23, 53, 89, 92, 46],
          [91, 57,  6, 58, 86],
          [50,  8, 24, 37, 44]],
 
         [[92, 29,  4, 49, 64],
          [29, 46, 35, 19, 88],
          [63, 82,  7, 46, 54],
          [57, 39, 50,  9,  6]],
 
         [[24, 24, 59, 78, 

## 2. Find the shape, rank, and size of the tensors you created in 1.

In [ ]:
print(f"Scalar: {scalar}\nScalar shape: {scalar.shape}\nScalar rank: {scalar.ndim}\nScalar size: {tf.size(scalar)}\n")
print(f"Vector: {vector}\nVector shape: {vector.shape}\nVector rank: {vector.ndim}\nVector size: {tf.size(vector)}\n")
print(f"Matrix: {matrix}\nMatrix shape: {matrix.shape}\nMatrix rank: {matrix.ndim}\nMatrix size: {tf.size(matrix)}\n")
print(f"Tensor: {tensor}\nTensor shape: {tensor.shape}\nTensor rank: {tensor.ndim}\nTensor size: {tf.size(tensor)}\n")

Scalar: [96]
Scalar shape: (1,)
Scalar rank: 1
Scalar size: 1

Vector: [75  5 78]
Vector shape: (3,)
Vector rank: 1
Vector size: 3

Matrix: [[96 51 38]
 [15  2 15]
 [49 59 19]
 [37 22 93]]
Matrix shape: (4, 3)
Matrix rank: 2
Matrix size: 12

Tensor: [[[[45 20 52 24 67]
   [ 9  6 96 92 27]
   [52 17 64 96 55]
   [62 12 29 93 47]]

  [[49 42 33 26 48]
   [39 62 36  2 85]
   [29 67  9 30  2]
   [37 16 27 46 87]]

  [[99 21 78  7 26]
   [23  5 43 54  5]
   [31  6 35 10 60]
   [61 61 20 95 56]]]


 [[[41 75 61 12 15]
   [23 53 89 92 46]
   [91 57  6 58 86]
   [50  8 24 37 44]]

  [[92 29  4 49 64]
   [29 46 35 19 88]
   [63 82  7 46 54]
   [57 39 50  9  6]]

  [[24 24 59 78 41]
   [99 81  0 22 87]
   [77 41  5 55 90]
   [77 84 18 69 59]]]]
Tensor shape: (2, 3, 4, 5)
Tensor rank: 4
Tensor size: 120



## 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [ ]:
rand_tensor_1 = tf.constant(tf.random.uniform(shape=[5, 300]))
rand_tensor_2 = tf.constant(tf.random.uniform(shape=[5, 300]))

rand_tensor_1, rand_tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.672454  , 0.77798486, 0.03375995, ..., 0.9338347 , 0.8705685 ,
         0.22951639],
        [0.3509519 , 0.64387655, 0.3880489 , ..., 0.015257  , 0.68726885,
         0.95157695],
        [0.5710547 , 0.73071456, 0.95567286, ..., 0.6335155 , 0.8449166 ,
         0.5725082 ],
        [0.9214455 , 0.4082582 , 0.8738706 , ..., 0.75351715, 0.87150145,
         0.3310882 ],
        [0.81754565, 0.09353554, 0.8405558 , ..., 0.22690332, 0.21470273,
         0.213593  ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.5856304 , 0.99483716, 0.46784043, ..., 0.7430197 , 0.9285357 ,
         0.8146846 ],
        [0.56168365, 0.7193047 , 0.18536437, ..., 0.35834217, 0.22342336,
         0.8487145 ],
        [0.11736929, 0.8434621 , 0.44691133, ..., 0.879455  , 0.13062525,
         0.7660978 ],
        [0.03889441, 0.7256719 , 0.35510492, ..., 0.8384137 , 0.7923595 ,
         0.9803941 ],
        [0.17135

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
# Transposing rand_tensor_1
tf.matmul(tf.transpose(rand_tensor_1), rand_tensor_2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.83388704, 2.3642933 , 1.2593724 , ..., 2.028474  , 1.9034622 ,
        2.5994046 ],
       [0.9349367 , 2.1831727 , 0.9888774 , ..., 1.8083845 , 1.3304808 ,
        2.187566  ],
       [0.52791995, 2.0537016 , 1.1308056 , ..., 1.869183  , 1.3423887 ,
        2.3701878 ],
       ...,
       [0.6979953 , 2.1023324 , 1.0729289 , ..., 1.92384   , 1.6602082 ,
        2.11239   ],
       [1.0657132 , 2.7823353 , 1.2998352 , ..., 2.4005651 , 1.866798  ,
        2.9026582 ],
       [0.7855694 , 1.7123848 , 0.734869  , ..., 1.3261284 , 0.8662883 ,
        1.8656552 ]], dtype=float32)>

In [ ]:
# Transposing rand_tensor_2
tf.matmul(rand_tensor_1, tf.transpose(rand_tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.51181 , 72.949524, 74.163795, 79.82292 , 76.28299 ],
       [82.603714, 73.400116, 77.209755, 78.34099 , 78.89096 ],
       [77.45411 , 71.920685, 70.62309 , 78.29396 , 75.31297 ],
       [79.3897  , 71.791046, 73.83662 , 79.70024 , 74.43523 ],
       [75.86035 , 71.11211 , 73.350555, 78.43787 , 75.31624 ]],
      dtype=float32)>

## 5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
# Transposing rand_tensor_1
tf.tensordot(tf.transpose(rand_tensor_1), rand_tensor_2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.83388704, 2.3642933 , 1.2593724 , ..., 2.028474  , 1.9034622 ,
        2.5994046 ],
       [0.9349367 , 2.1831727 , 0.9888774 , ..., 1.8083845 , 1.3304808 ,
        2.187566  ],
       [0.52791995, 2.0537016 , 1.1308056 , ..., 1.869183  , 1.3423887 ,
        2.3701878 ],
       ...,
       [0.6979953 , 2.1023324 , 1.0729289 , ..., 1.92384   , 1.6602082 ,
        2.11239   ],
       [1.0657132 , 2.7823353 , 1.2998352 , ..., 2.4005651 , 1.866798  ,
        2.9026582 ],
       [0.7855694 , 1.7123848 , 0.734869  , ..., 1.3261284 , 0.8662883 ,
        1.8656552 ]], dtype=float32)>

In [ ]:
# Transposing rand_tensor_2
tf.tensordot(rand_tensor_1, tf.transpose(rand_tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.51181 , 72.949524, 74.163795, 79.82292 , 76.28299 ],
       [82.603714, 73.400116, 77.209755, 78.34099 , 78.89096 ],
       [77.45411 , 71.920685, 70.62309 , 78.29396 , 75.31297 ],
       [79.3897  , 71.791046, 73.83662 , 79.70024 , 74.43523 ],
       [75.86035 , 71.11211 , 73.350555, 78.43787 , 75.31624 ]],
      dtype=float32)>

## 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [ ]:
rand_tensor_3 = tf.constant(tf.random.uniform(shape=[224, 224, 3]))
rand_tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8202617 , 0.22106671, 0.81801796],
        [0.84848654, 0.6710081 , 0.87413895],
        [0.24310064, 0.5802394 , 0.18229508],
        ...,
        [0.95663023, 0.16247034, 0.04997659],
        [0.3682282 , 0.27978957, 0.9815496 ],
        [0.47326195, 0.82216835, 0.9920951 ]],

       [[0.10723591, 0.24188769, 0.6917293 ],
        [0.5992284 , 0.95643866, 0.43942833],
        [0.91039264, 0.9359051 , 0.9482014 ],
        ...,
        [0.7475804 , 0.9248016 , 0.01162386],
        [0.7813721 , 0.50152624, 0.5868045 ],
        [0.75498307, 0.762112  , 0.65984285]],

       [[0.32984543, 0.87434196, 0.2770182 ],
        [0.20068657, 0.98429894, 0.30171156],
        [0.28975666, 0.11703563, 0.8368559 ],
        ...,
        [0.56420374, 0.90473616, 0.9468242 ],
        [0.5742885 , 0.28051972, 0.4850217 ],
        [0.5888672 , 0.18018329, 0.11591721]],

       ...,

       [[0.9226384 , 0.3390962 , 0.9217565 ],
        [0.78

## 7. Find the min and max values of the tensor you crated in 6.

In [ ]:
print(f"Minimum value of rand_tensor_3: {tf.reduce_min(rand_tensor_3)}")
print(f"Maximum value of rand_tensor_3: {tf.reduce_max(rand_tensor_3)}")

Minimum value of rand_tensor_3: 6.198883056640625e-06
Maximum value of rand_tensor_3: 0.9999980926513672


## 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [ ]:
rand_tensor_4 = tf.constant(tf.random.uniform(shape=[1, 224, 224, 3]))
squeezed_tensor = tf.squeeze(rand_tensor_4)
print(f"Original tensor shape: {rand_tensor_4.shape}")
print(f"Squeezed tensor shape: {squeezed_tensor.shape}")

Original tensor shape: (1, 224, 224, 3)
Squeezed tensor shape: (224, 224, 3)


## 9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [ ]:
rand_tensor_5 = tf.constant(np.random.randint(0, 100, size=(10)))
print(f"Original tensor: {rand_tensor_5}")
print(f"Index of max value of rand_tensor_5 (index values start at 0): {tf.argmax(rand_tensor_5)}")

Original tensor: [ 6 53 74 32 39 36 44 94  8 28]
Index of max value of rand_tensor_5 (index values start at 0): 7


## 10. One-hot encode the tensor you created in 9.

In [ ]:
tf.one_hot(rand_tensor_5, depth=100)

<tf.Tensor: shape=(10, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.,